name: ESLint Validation

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install package.json dependecies
        run: |
          npm install
          npx eslint .
      
      - name: Run ESLint
        run: npx eslint .
        continue-on-error: true

      - name: Check ESLint results and fail if errors found
        run: |
          if [$? -ne 0 ]; then
            exit 1
          fi
        